USE [master]
GO
/****** Object:  Database [KUTUPHANEDB]    Script Date: 22.07.2025 11:38:39 ******/
CREATE DATABASE [KUTUPHANEDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'KUTUPHANEDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\KUTUPHANEDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'KUTUPHANEDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\KUTUPHANEDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [KUTUPHANEDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [KUTUPHANEDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [KUTUPHANEDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [KUTUPHANEDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [KUTUPHANEDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [KUTUPHANEDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [KUTUPHANEDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [KUTUPHANEDB] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [KUTUPHANEDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [KUTUPHANEDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [KUTUPHANEDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [KUTUPHANEDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [KUTUPHANEDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [KUTUPHANEDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [KUTUPHANEDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [KUTUPHANEDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [KUTUPHANEDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [KUTUPHANEDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [KUTUPHANEDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [KUTUPHANEDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [KUTUPHANEDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [KUTUPHANEDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [KUTUPHANEDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [KUTUPHANEDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [KUTUPHANEDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [KUTUPHANEDB] SET  MULTI_USER 
GO
ALTER DATABASE [KUTUPHANEDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [KUTUPHANEDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [KUTUPHANEDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [KUTUPHANEDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [KUTUPHANEDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [KUTUPHANEDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [KUTUPHANEDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [KUTUPHANEDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [KUTUPHANEDB]
GO
/****** Object:  Table [dbo].[Kategoriler]    Script Date: 22.07.2025 11:38:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Kategoriler](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Ad] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KITAPLAR]    Script Date: 22.07.2025 11:38:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KITAPLAR](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Ad] [nvarchar](200) NOT NULL,
	[SayfaSayisi] [int] NULL,
	[YazarID] [int] NOT NULL,
	[Aciklama] [nvarchar](max) NULL,
	[GorselUrl] [nvarchar](max) NULL,
	[KategoriId] [int] NULL,
	[Icerik] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Kullanicilar]    Script Date: 22.07.2025 11:38:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Kullanicilar](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[KullaniciAdi] [nvarchar](100) NOT NULL,
	[Eposta] [nvarchar](150) NOT NULL,
	[Sifre] [nvarchar](100) NOT NULL,
	[Rol] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Eposta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[KullaniciAdi] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[YAZARLAR]    Script Date: 22.07.2025 11:38:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[YAZARLAR](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AdSoyad] [nvarchar](150) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Kullanicilar] ADD  DEFAULT ('Uye') FOR [Rol]
GO
ALTER TABLE [dbo].[KITAPLAR]  WITH CHECK ADD  CONSTRAINT [FK_KITAPLAR_YAZARLAR] FOREIGN KEY([YazarID])
REFERENCES [dbo].[YAZARLAR] ([ID])
GO
ALTER TABLE [dbo].[KITAPLAR] CHECK CONSTRAINT [FK_KITAPLAR_YAZARLAR]
GO
ALTER TABLE [dbo].[KITAPLAR]  WITH CHECK ADD  CONSTRAINT [FK_Kitaplar_Kategoriler] FOREIGN KEY([KategoriId])
REFERENCES [dbo].[Kategoriler] ([Id])
GO
ALTER TABLE [dbo].[KITAPLAR] CHECK CONSTRAINT [FK_Kitaplar_Kategoriler]
GO
USE [master]
GO
ALTER DATABASE [KUTUPHANEDB] SET  READ_WRITE 
GO
